language: generic
sudo: required
services:
  - docker

before_install:
  - cd section6/frontend
  - docker build -t kojotak/udk8s -f Dockerfile.dev .

script:
  - docker run -e CI=true kojotak/udk8s npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udk8s"
  env: "Udk8s-env"
  bucket_name: "elasticbeanstalk-us-east-2-606471208599"
  bucket_path: "udk8s"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"