language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kojotak/udk8s -f section6/frontend/Dockerfile.dev .

script:
  - cd section6/frontend
  - docker run -e CI=true kojotak/udk8s npm run test