# development docker image
FROM node:alpine

WORKDIR '/app'

#dependencies
COPY package.json .
RUN npm install

#no need to copy everthing, since we are mapping current filesystem inside docker image
#but this is just a reminder, that in production, we should copy our application into docker
COPY . .

CMD ["npm","run","start"]